# Generated by Django 3.2 on 2021-04-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_auto_20210426_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='img',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='tel',
            field=models.CharField(default=' ', max_length=8),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
