# Generated by Django 3.2 on 2021-04-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_auto_20210426_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='tel',
            field=models.CharField(default=' ', max_length=9),
        ),
    ]
