# Generated by Django 3.2 on 2021-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_auto_20210426_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='img',
            field=models.ImageField(blank=True, default=' ', upload_to=''),
        ),
    ]
