# Generated by Django 3.2 on 2021-05-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=' ', upload_to=''),
        ),
    ]
